language: scala

scala: 
  - 2.10.0

notifications: 
  email: 
    recipients: 
      - sxb5828@rit.edu
    on_success: always
    on_failure: always

script: 
#build installer 
  mvn clean package -f smmonitoring/pom.xml

#build 
