language: scala

scala: 
  - 2.10.0

notifications: 
  email: 
    recipients: 
      - sxb5828@rit.edu
    on_success: always
    on_failure: always
    on_error: always

script: 
  #mvn assembly:assembly -DdescriptorId=jar-with-dependencies
  #build setup   
  - mvn clean package -f kimchisetup/pom.xml

  #build server 
  - mvn clean package -f kimchiserver/pom.xml

  #build client 
  - mvn clean package -f kimchiclient/pom.xml
