language: scala

scala: 
  - 2.10.0

notifications: 
  email: 
    recipients: 
      - sxb5828@rit.edu
    on_success: always
    on_failure: always

#Build everything
script: 
#build installer 
  mvn clean package -f smmonitoring/pom.xml

#build server 
  mvn clean package -f smmmonitoring/pom.xml

#build client 
  mvn clean package -f smmonitoringclient/pom.xml
 
