language: scala

scala: 
  - 2.10.0

notifications: 
  email: 
    recipients: 
      - sxb5828@rit.edu
    on_success: always
    on_failure: always

script:
  #build setup   
  - mvn clean package -f smmonitoringsetup/pom.xml

  #build server 
  - mvn clean package -f smmonitoring/pom.xml

  #build client 
  - mvn clean package -f smmonitoringclient/pom.xml
